title: Homepage of Guillaume Lecué
author: Guillaume Lecué
email: guillaume.lecue@ensae.fr
description: Empirical processes theory; Learning theory; Compressed sensing; aggregation; phase retreival; Minimax;
baseurl: ""
url: "http://lecueguillaume.github.io/"
github_username:  lecueguillaume
#twitter_username: Guillaume_Lecue

# Build settings
markdown: kramdown
permalink: pretty
#paginate: 5
#exclude: ["node_modules"]
#encoding: UTF-8

#name: Guillaume Lecué, recent works
gems:
 - jekyll-mentions
 - jemoji
 - jekyll-redirect-from
 - jekyll-sitemap
 - jekyll-feed